### ISSUE TITLE
Building a real-world site

### ISSUE THREAD

**Issue by ppass5** [CouchCMS/Documentation#13]
**Page:** `http://docs.couchcms.com/tutorials/portfolio-site/building-a-real-world-site.html`

I'm extremely new at this and trying to install Couch for the first time. I've renamed my config.example to config.php and in the tutorial it says to edit MySQL database name for my local database. Where do I find "MySQL" database name? So far I have the files stored on a dropbox account connected to my computer and have been accessing them there until I ftp them to the web. I've downloaded XAMPP but unsure how to proceed.

**Comment by cheesypoof** [comment]
Hi @ppass5. Please post to our [forum](http://www.couchcms.com/forum/) for support-related matters.
