### ISSUE TITLE
type = 'text'

### ISSUE THREAD

**Issue by glennwilton** [CouchCMS/Documentation#15]
**Page:** `http://docs.couchcms.com/tags-reference/editable/text.html`

text:
If you wish to use this region to input numeric values (e.g. age or salary), set the type to either **numeric** or decimal (if the value can be fractional).

should read
set the type to either **'integer'** or 'decimal' (if the value can be fractional).

**Comment by cheesypoof** [comment]
Thank you for the report. This has been addressed, albeit just a tad late.
