### ISSUE TITLE
On Page Editing

### ISSUE THREAD

**Issue by TheRealKaufmann** [CouchCMS/Documentation#25]
**Page:** ` https://docs.couchcms.com/concepts/on-page-editing.html `

Hello Community!
I followed the exact steps in order to edit the content on page. However, inline-editing works flawlessly but the popup-editing doesn't. Every time I click on Edit on a specified popup-edit, I see the popup with an error that says "No renderable template found for 'inline_content_form". I already Googled for hours but do not find any solution.

Thanks in advance for any help.

Cheers,
Tom

**Comment by kksidd** [comment]
Hi,

Just tested this feature with the Miniport demo site (https://docs.couchcms.com/concepts/on-page-editing.html) using Couch v2.2RC1 (latest from GitHub as of this date).

Everything appears to be working just fine to me.

Could you please test using the Couch version indicated above?
Do let me know how it goes.

**Comment by TheRealKaufmann** [comment]
> Hi,
> 
> Just tested this feature with the Miniport demo site (https://docs.couchcms.com/concepts/on-page-editing.html) using Couch v2.2RC1 (latest from GitHub as of this date).
> 
> Everything appears to be working just fine to me.
> 
> Could you please test using the Couch version indicated above?
> Do let me know how it goes.



Thanks for your quick reply man!
I ensured that my version of couch is up to date. Do you have any Idea to which script this error could point?

Cheers,
Tom

**Comment by kksidd** [comment]
Hi Tom,

Let us continue this conversation over at our forums (https://www.couchcms.com/forum/), shall we?
You can, if you so wish, PM me the FTP+Couch access creds to your site and I'll take a look at the issue.
