### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by jose-mario-jr** [CouchCMS/Documentation#29]
**Page:** ` https://docs.couchcms.com/tutorials/portfolio-site/contact-form.html `

I am not getting the emails, even after I switch the K_USE_ALTERNATIVE_MTA to '1' in config.php

**Comment by kksidd** [comment]
Please see [https://www.couchcms.com/forum/viewtopic.php?f=5&t=10750](https://www.couchcms.com/forum/viewtopic.php?f=5&t=10750) where we discuss ways to debug this problem. 

Hope it helps.
