### ISSUE TITLE
Starting off simple - the About-Us page

### ISSUE THREAD

**Issue by RedstoneFiend** [CouchCMS/Documentation#4]
**Page:** `http://docs.couchcms.com/tutorials/portfolio-site/about-us.html`

These two boilerplate lines of code is the only PHP that you should ever need to write to work with couch.

Replace is with are:

These two boilerplate lines of code are the only PHP that you should ever need to write to work with couch.

**Comment by cheesypoof** [comment]
Thank you @RedstoneFiend.
