### ISSUE TITLE
Diving deep - the Blog (Part 1) - Embed example

### ISSUE THREAD

**Issue by NickCis** [CouchCMS/Documentation#6]
**Page:** `http://docs.couchcms.com/tutorials/portfolio-site/blog.html`

According to the [embed documentation](http://docs.couchcms.com/tags-reference/embed.html) by default embed path are from `couch/snippets/` folder. In order to change this default behavior `12b. K_SNIPPETS_DIR` configuration item (in the `config.php`) must be setted.

```
    // 12b.
    // Folder containing the embedded snippets if not using the default 'snippets' folder within 'couch'.
    // Should be relative to your site. No leading or trailing slashes please.
    define( 'K_SNIPPETS_DIR', '' );
```

(The code responsable of this behavior is `tags.php:383`)

The tutorial should warn that this option must be configured in order to work.

**Comment by cheesypoof** [comment]
Would adding

> See [embed](http://docs.couchcms.com/tags-reference/embed.html) tag for snippets folder customization instructions.

after

> We'll use the embed tag to display _blog_list.html_ in the list-view.
> Move _blog_list.html_ into the snippets folder found within the couch folder (this is not mandatory, but files kept in this folder are kept safe from being accessed directly by the _.htaccess_ file present within the folder and hence is desirable).

satisfy your concern?

**Comment by NickCis** [comment]
Yes, thanks!

**Comment by NickCis** [comment]
Yes, thanks!
