### ISSUE TITLE
Diving deep - the Blog (Part 1)

### ISSUE THREAD

**Issue by leonhardvoos** [CouchCMS/Documentation#7]
**Page:** `http://docs.couchcms.com/tutorials/portfolio-site/blog.html`

In the section "Defining editable regions" there are two editor screenshots of the first lines of blog.php.
The second screenshot uses the template tag with options clonable and commentable. I think this is wrong here and should be changed as in first screenshot.

Leo

**Comment by kksidd** [comment]
Thank you for the heads-up, Leon.
Have fixed the issue.
